---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scaling-demo
  name: demo
  namespace: scaling-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-demo
  template:
    metadata:
      labels:
        app: scaling-demo
    spec:
      containers:
      - image: thorstenhans/aks-scaling-demo:0.0.1
        name: aks-auto-scaler-demo
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /status/health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-hpa
  namespace: scaling-demo
  labels:
    app: scaling-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
