---       
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scaling-demo
  name: demo
  namespace: scaling-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scaling-demo
  template:
    metadata:
      labels:
        app: scaling-demo
    spec:
      containers:
      - image: thorstenhans/aks-scaling-demo:0.0.1
        name: aks-auto-scaler-demo
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /status/health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 800m
            memory: 1000Mi
          requests:
            cpu: 400m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: scaling-demo-service
  namespace: scaling-demo
  # The following two lines are required when using an ingress controller
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: scaling-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: scaling-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-route
  namespace: scaling-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /(/|$)(.*)
        backend:
          service:
            name: scaling-demo-service
            port:
              number: 80
